### ISSUE TITLE
测试formart格式错误,exchange死掉

### ISSUE THREAD

**Issue by zhangyulin** [adleida/adx-nodejs#4]
跑所有case的循环测试, adkit运行到 formart 051的case时就会死掉;

```
debug: request:  user_id=554b4509d25b48482e7f6bd9, cur=CNY, is_test=1, cid=9875, type=1, count=2, floor=1.5, latitude=14.782567058496316, country=Chile, longtitude=22.852963611150223, city=Jaclynmouth, sdk=bangbang, id=e24f659e-5fb3-4757-ac4a-986c1544d3cc
verbose: dsp undefined returned bid response
debug: response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

info: dsp undefined returned invalid response
debug:  SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/ubuntu/adx-nodejs/engine/engine.js:122:49)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
info: reconfigure engine
verbose: configure engine dsp list
verbose: engine dsp list now are  bid_host=dsp, bid_port=6001, bid_path=/res/v2/110
verbose: request not valide
debug:  user_id=554ad8ccd25b4819bae08337, cur=CNY, is_test=1, device_id_enc=1, network_id=70123, brand=Prosacco, resolution_w=242, os_version=4.1.1, resolution_h=5132, device_type=1, model=Vennie, os=ANDROID, delected_language=pt_RS, device_id=dfd2a399e5a3d519e98a38906c44a0bd, cid=2081, count=1, floor=1.3, latitude=72.70559754856825, country=Israel, longtitude=92.65878759419584, city=Port Breannatown, sdk=bangbang
error: engine doesn't have auctioneer for ad type undefined
info: start new auction e1a63b7f-9644-400e-a9df-e8c1e78e0d98
verbose: send bid request to dsp undefined ==> dsp:6001/res/v2/110
debug: request:  user_id=554ad8ccd25b4819bae08337, cur=CNY, is_test=1, device_id_enc=1, network_id=70123, brand=Prosacco, resolution_w=242, os_version=4.1.1, resolution_h=5132, device_type=1, model=Vennie, os=ANDROID, delected_language=pt_RS, device_id=dfd2a399e5a3d519e98a38906c44a0bd, cid=2081, count=1, floor=1.3, latitude=72.70559754856825, country=Israel, longtitude=92.65878759419584, city=Port Breannatown, sdk=bangbang, id=e1a63b7f-9644-400e-a9df-e8c1e78e0d98
verbose: dsp undefined returned bid response
debug: response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

info: dsp undefined returned invalid response
debug:  SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/ubuntu/adx-nodejs/engine/engine.js:122:49)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

/home/ubuntu/adx-nodejs/engine/engine.js:187
        var result = auctioneer.handle(request, responses, self);
                                ^
TypeError: Cannot call method 'handle' of undefined
    at /home/ubuntu/adx-nodejs/engine/engine.js:187:33
    at IncomingMessage.<anonymous> (/home/ubuntu/adx-nodejs/engine/engine.js:136:25)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

npm ERR! Dangerous@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Dangerous@0.0.0 start script.
npm ERR! This is most likely a problem with the Dangerous package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls Dangerous
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-53-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/ubuntu/adx-nodejs
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/adx-nodejs/npm-debug.log
npm ERR! not ok code 0

```

**Comment by lkiversonlk** [comment]
Fixed in commit 7325bfe7a8b20e695d113845611826713189cc94.

The engine doesn't stop auctioning if there were no valid auctioneer for this request type.

@zhangyulin
